### ISSUE TITLE
error when launching tool fb.py

### ISSUE THREAD

**Issue by chekamarue** [fuzzbunch/fuzzbunch#10]
Hello, i'am using python 2.6 with pywin32 in both windows 7 x86 and got this error 

> Traceback (most recent call last):
  File "C:\Users\Chekamarue\Desktop\fuzzbunch-master\fuzzbunch-master\fb.py", li
ne 37, in <module>
    from fuzzbunch.edfplugin import EDFPlugin
  File "C:\Users\Chekamarue\Desktop\fuzzbunch-master\fuzzbunch-master\fuzzbunch\
edfplugin.py", line 5, in <module>
    import edfexecution
  File "C:\Users\Chekamarue\Desktop\fuzzbunch-master\fuzzbunch-master\fuzzbunch\
edfexecution.py", line 30, in <module>
    import win32pipe
ImportError: No module named win32pipe

**Comment by chekamarue** [comment]
solved the previous problem by follow this 
[https://stackoverflow.com/questions/7238403/import-win32api-error-in-python-2-6](url)

right after that i got the following error...

> [*] Loading Plugins
===============================================================
=
= Encountered an unhandled error.  Please provide the following
= information to the developer
=
===============================================================
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\New folder\fuzzbunch-master\fuzzbunch\exc
eption.py", line 66, in wrap
    ret = fn(*args, **kwargs)
  File "fb.py", line 83, in setup_and_run
    load_plugins(fb)
  File "fb.py", line 72, in load_plugins
    addplugins(fb, "ListeningPost", LP_DIR,      EDFPlugin)
  File "C:\Users\Administrator\Desktop\New folder\fuzzbunch-master\fuzzbunch\plu
ginfinder.py", line 78, in addplugins
    plugins = getpluginlist(location, bin)
  File "C:\Users\Administrator\Desktop\New folder\fuzzbunch-master\fuzzbunch\plu
ginfinder.py", line 36, in getpluginlist
    fblist     = getextensionfiles(location, FB_CONFIG_EXT)         # get list o
f .fb files
  File "C:\Users\Administrator\Desktop\New folder\fuzzbunch-master\fuzzbunch\plu
ginfinder.py", line 21, in getextensionfiles
    for file in os.listdir(location)
WindowsError: [Error 3] The system cannot find the path specified: 'C:\\Users\\A
dministrator\\Desktop\\New folder\\fuzzbunch-master\\listeningposts/*.*'<

**Comment by chekamarue** [comment]
solved using [https://github.com/knightmare2600/ShadowBrokers/blob/master/Lost_In_Translation/FUZZBUNCH.bat](url)
