### ISSUE TITLE
problem while starting the tool 

### ISSUE THREAD

**Issue by abh1177** [fuzzbunch/fuzzbunch#2]
**i` had the same problem in the previous issue 
and i did install python 2.6.x and pywin32 (both 32bit) and i tasted it on 4 Os's (win xp, 7, 10 and linux)
and when i run fb.py this comes up** 

```
--[ Version 3.5.1

[*] Loading Plugins
===============================================================
=
= Encountered an unhandled error.  Please provide the following
= information to the developer
=
===============================================================
Traceback (most recent call last):
  File "C:\Users\abh\Desktop\fuzzbunch-master\fuzzbunch\exception.py", line 66, in wrap
    ret = fn(*args, **kwargs)
  File "C:\Users\abh\Desktop\fuzzbunch-master\fb.py", line 83, in setup_and_run
    load_plugins(fb)
  File "C:\Users\abh\Desktop\fuzzbunch-master\fb.py", line 72, in load_plugins
    addplugins(fb, "ListeningPost", LP_DIR,      EDFPlugin)
  File "C:\Users\abh\Desktop\fuzzbunch-master\fuzzbunch\pluginfinder.py", line 78, in addplugins
    plugins = getpluginlist(location, bin)
  File "C:\Users\abh\Desktop\fuzzbunch-master\fuzzbunch\pluginfinder.py", line 36, in getpluginlist
    fblist     = getextensionfiles(location, FB_CONFIG_EXT)         # get list of .fb files
  File "C:\Users\abh\Desktop\fuzzbunch-master\fuzzbunch\pluginfinder.py", line 21, in getextensionfiles
    for file in os.listdir(location)
WindowsError: [Error 3] The system cannot find the path specified: 'C:\\Users\\abh\\Desktop\\fuzzbunch-master\\listeningposts/*.*'
```

**Comment by hiw0rld** [comment]
make dir listeningposts can solve it

**Comment by abh1177** [comment]
worked like magic 
thx 
how can i close this issue ?

**Comment by NeoZion** [comment]
make dir listeningposts can solve it in fuzzbunch-master\\

**Comment by xNymia** [comment]
Addressed here: #4

**Comment by anonhazard** [comment]
I have this problem and pywin32 is installed normally:
Traceback (most recent call last):
  File "fb.py", line 37, in <module>
    from fuzzbunch.edfplugin import EDFPlugin
  File "/root/Desktop/HServer/shadowbroker/windows/fuzzbunch/edfplugin.py", line 7, in <module>
    from plugin       import Plugin
  File "/root/Desktop/HServer/shadowbroker/windows/fuzzbunch/plugin.py", line 8, in <module>
    import truantchild
  File "/root/Desktop/HServer/shadowbroker/windows/fuzzbunch/truantchild.py", line 8, in <module>
    import exma
  File "/root/Desktop/HServer/shadowbroker/windows/fuzzbunch/exma.py", line 19, in <module>
    _libraries['exma.dll'] = ctypes.CDLL('libexma.so.1')
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libexma.so.1: cannot open shared object file: No such file or directory

**Comment by RoARene317** [comment]
try reinstall python 2.6 (32bit ver) and pywin32

**Comment by anonhazard** [comment]
I have the most current kali version and I always perform system updates, and python 2.6, 2.7 and so are installed normally. But such a mistake insists on appearing ...

**Comment by RoARene317** [comment]
Better if you use windows instead kali
because you no need msfconsole to do that thing
Just use Danderspritz (start.jar) to RAT the pc target
